# Generated by Django 4.1.4 on 2023-01-01 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Mężczyzna", "Mężczyzna"), ("Kobieta", "Kobieta")],
                default="Mężczyzna",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="player_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="player_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
