# Generated by Django 4.1.4 on 2022-12-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="belt",
            field=models.CharField(
                choices=[
                    ("1", "Biały"),
                    ("2", "Niebieski"),
                    ("3", "Purpurowy"),
                    ("4", "Brązowy"),
                    ("5", "Czarny"),
                ],
                max_length=30,
            ),
        ),
    ]
