# Generated by Django 4.1.4 on 2022-12-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_alter_player_belt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="belt",
            field=models.CharField(
                choices=[
                    ("Biały", "Biały"),
                    ("Niebieski", "Niebieski"),
                    ("Purpurowy", "Purpurowy"),
                    ("Brązowy", "Brązowy"),
                    ("Czarny", "Czarny"),
                ],
                max_length=30,
            ),
        ),
    ]
