# Generated by Django 4.1.4 on 2023-01-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_player_birth_date_player_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Mężczyzna"), ("K", "Kobieta")],
                default="M",
                max_length=10,
            ),
        ),
    ]
