# Generated by Django 4.1.4 on 2022-12-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_alter_player_belt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="belt",
            field=models.CharField(
                choices=[
                    ("Biały", "Biały"),
                    ("Niebieski", "Niebieski"),
                    ("Purpurowy", "Purpurowy"),
                    ("Brązowy", "Brązowy"),
                    ("Czarny", "Czarny"),
                ],
                default="Biały",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="stripes",
            field=models.CharField(
                choices=[("0", "0"), ("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                default="0",
                max_length=1,
            ),
        ),
    ]
