# Generated by Django 4.1.4 on 2023-01-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_alter_player_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Mężczyzna", "Mężczyzna"), ("Kobieta", "Kobieta")],
                default="Mężczyzna",
                max_length=10,
            ),
        ),
    ]
