# Generated by Django 4.1.4 on 2023-01-01 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0004_alter_player_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="first_training",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="last_training",
            field=models.DateField(blank=True, null=True),
        ),
    ]
