# Generated by Django 4.1.4 on 2023-01-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0006_alter_player_first_training"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="player_created",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="player",
            old_name="player_modified",
            new_name="modified",
        ),
        migrations.AddField(
            model_name="player",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
