# Generated by Django 4.1.4 on 2023-01-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0008_player_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="player",
            name="subscription_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1 Wejście", "1 Wejście"),
                    ("4 Wejścia", "4 Wejścia"),
                    ("8 Wejść", "8 Wejść"),
                    ("15 Wejść", "15 Wejść"),
                    ("OPEN", "OPEN"),
                    ("Dzieci i młodzież", "Dzieci i młodzież"),
                ],
                default="1 Wejście",
                max_length=30,
            ),
        ),
    ]
