# Generated by Django 4.1.4 on 2023-01-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0009_alter_player_options_player_subscription_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
