# Generated by Django 4.1.4 on 2023-01-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0010_player_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="recent_left_entries",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="sub_month",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="total_entries",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
