# Generated by Django 4.1.4 on 2023-01-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0011_player_recent_left_entries_player_sub_month_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "subscription_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1 Wejście", "1 Wejście"),
                            ("4 Wejścia", "4 Wejścia"),
                            ("8 Wejść", "8 Wejść"),
                            ("15 Wejść", "15 Wejść"),
                            ("OPEN", "OPEN"),
                            ("Dzieci i młodzież", "Dzieci i młodzież"),
                        ],
                        default="1 Wejście",
                        max_length=30,
                    ),
                ),
                ("recent_left_entries", models.PositiveIntegerField(default=0)),
                ("total_entries", models.PositiveIntegerField(default=0)),
                ("sub_month", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="player",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="player",
            name="created",
        ),
        migrations.RemoveField(
            model_name="player",
            name="email",
        ),
        migrations.RemoveField(
            model_name="player",
            name="first_training",
        ),
        migrations.RemoveField(
            model_name="player",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="player",
            name="last_training",
        ),
        migrations.RemoveField(
            model_name="player",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="player",
            name="phone_number",
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Mężczyzna", "Mężczyzna"), ("Kobieta", "Kobieta")],
                        default="Mężczyzna",
                        max_length=10,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("first_training", models.DateField(blank=True, null=True)),
                ("last_training", models.DateField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="players.player"
                    ),
                ),
            ],
        ),
    ]
