# Generated by Django 4.1.4 on 2023-01-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0012_membershipfee_remove_player_birth_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="active",
        ),
        migrations.RemoveField(
            model_name="player",
            name="recent_left_entries",
        ),
        migrations.RemoveField(
            model_name="player",
            name="sub_month",
        ),
        migrations.RemoveField(
            model_name="player",
            name="subscription_type",
        ),
        migrations.RemoveField(
            model_name="player",
            name="total_entries",
        ),
        migrations.AddField(
            model_name="membershipfee",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="players.player",
            ),
        ),
    ]
