# Generated by Django 4.1.4 on 2023-01-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0014_alter_personalinfo_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membershipfee",
            name="id",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="id",
        ),
        migrations.AlterField(
            model_name="membershipfee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="players.player",
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="players.player",
            ),
        ),
    ]
