# Generated by Django 4.1.4 on 2023-01-26 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0015_remove_membershipfee_id_remove_personalinfo_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="players.player",
                    ),
                ),
                ("total_entries", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="membershipfee",
            name="total_entries",
        ),
    ]
